# Welcome to Jekyll!

# Website settings
title: "Building Integrity"
description: "Jack's blog,use Jekyll and github pages."
keywords: "Jack,Jalpc,blog,Jekyll,github,gh-pages"
#baseurl: "http://wonderware.github.io/building-integrity/_site/"
#url: "http://wonderware.github.io"
url: "http://127.0.0.1:4000"
baseurl: "/"

# landing page
landing:
  home: 'Home'
  our_mission: 'Our Mission'
  career: 'Career'
  skills: 'Skills'
  projects: 'Project'
  blog: 'Blog'
  link: 'Link'

# google analytics
ga:
  id: UA-73784599-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
